<p style="text-align:center">
    <a href="https://skills.network" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo"  />
    </a>
</p>

# **Data Wrangling Lab**

Estimated time needed: **45** minutes

In this lab, you will perform data wrangling tasks to prepare raw data for analysis. Data wrangling involves cleaning, transforming, and organizing data into a structured format suitable for analysis. This lab focuses on tasks like identifying inconsistencies, encoding categorical variables, and feature transformation.

## Objectives

After completing this lab, you will be able to:

- Identify and remove inconsistent data entries.

- Encode categorical variables for analysis.

- Handle missing values using multiple imputation strategies.

- Apply feature scaling and transformation techniques.

#### Intsall the required libraries

In [56]:
!pip install pandas
!pip install numpy
!pip install matplotlib
!pip install seaborn
!pip install scikit-learn

Requirement already satisfied: pandas in /opt/conda/lib/python3.12/site-packages (3.0.2)
Requirement already satisfied: numpy>=1.26.0 in /opt/conda/lib/python3.12/site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: numpy in /opt/conda/lib/python3.12/site-packages (2.4.4)
Requirement already satisfied: matplotlib in /opt/conda/lib/python3.12/site-packages (3.10.9)
Requirement already satisfied: contourpy>=1.0.1 in /opt/conda/lib/python3.12/site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /opt/conda/lib/python3.12/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /opt/conda/lib/python3.12/site-packages (from matplotlib) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /opt/conda/lib/python3.12/site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: numpy>=1.23 in /opt/conda/lib/python3.12/site-packages (from matplotlib) (2.4.4)
Requirement already satisfied: packaging>=20.0 in /opt/conda/lib/python3.12/site-packages (from matplotlib) (24.2)
Requirement already satisfied: pillow>=8 in /opt/conda/lib/python3.12/site-packages (from matplotlib) (12.2.0)
Requirement already satisfied: pyparsing>=3 in /opt/conda/lib/python3.12/site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /opt/conda/lib/python3.12/site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.12/site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Requirement already satisfied: seaborn in /opt/conda/lib/python3.12/site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in /opt/conda/lib/python3.12/site-packages (from seaborn) (2.4.4)
Requirement already satisfied: pandas>=1.2 in /opt/conda/lib/python3.12/site-packages (from seaborn) (3.0.2)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in /opt/conda/lib/python3.12/site-packages (from seaborn) (3.10.9)
Requirement already satisfied: contourpy>=1.0.1 in /opt/conda/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /opt/conda/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /opt/conda/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /opt/conda/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /opt/conda/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (24.2)
Requirement already satisfied: pillow>=8 in /opt/conda/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.2.0)
Requirement already satisfied: pyparsing>=3 in /opt/conda/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /opt/conda/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.12/site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Requirement already satisfied: scikit-learn in /opt/conda/lib/python3.12/site-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in /opt/conda/lib/python3.12/site-packages (from scikit-learn) (2.4.4)
Requirement already satisfied: scipy>=1.10.0 in /opt/conda/lib/python3.12/site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in /opt/conda/lib/python3.12/site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in /opt/conda/lib/python3.12/site-packages (from scikit-learn) (3.6.0)

## Tasks

#### Step 1: Import the necessary module.

### 1. Load the Dataset

<h5>1.1 Import necessary libraries and load the dataset.</h5>

Ensure the dataset is loaded correctly by displaying the first few rows.

In [19]:
# Import necessary libraries
import pandas as pd

# Load the Stack Overflow survey data
dataset_url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/n01PQ9pSmiRX6520flujwQ/survey-data.csv"
df = pd.read_csv(dataset_url)

# Display the first few rows
display(df.head())

,ResponseId,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,...,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,Under 18 years old,"Employed, full-time",Remote,Apples,Hobby,Primary/elementary school,Books / Physical media,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
2,3,I am a developer by profession,45-54 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,...,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
3,4,I am learning to code,18-24 years old,"Student, full-time",NaN,Apples,NaN,Some college/university study without earning ...,"Other online resources (e.g., videos, blogs, f...",Stack Overflow;How-to videos;Interactive tutorial,...,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN,NaN
4,5,I am a developer by profession,18-24 years old,"Student, full-time",NaN,Apples,NaN,"Secondary school (e.g. American high school, G...","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,...,NaN,NaN,NaN,NaN,NaN,NaN,Too short,Easy,NaN,NaN

#### 2. Explore the Dataset

<h5>2.1 Summarize the dataset by displaying the column data types, counts, and missing values.</h5>

In [20]:
# Write your code here
# 2.1 Summarize the dataset
print(df.info(verbose=True, show_counts=True))

<class 'pandas.DataFrame'>
RangeIndex: 65437 entries, 0 to 65436
Data columns (total 114 columns):
 #    Column                          Non-Null Count  Dtype
---   ------                          --------------  -----
 0    ResponseId                      65437 non-null  int64
 1    MainBranch                      65437 non-null  str
 2    Age                             65437 non-null  str
 3    Employment                      65437 non-null  str
 4    RemoteWork                      54806 non-null  str
 5    Check                           65437 non-null  str
 6    CodingActivities                54466 non-null  str
 7    EdLevel                         60784 non-null  str
 8    LearnCode                       60488 non-null  str
 9    LearnCodeOnline                 49237 non-null  str
 10   TechDoc                         40897 non-null  str
 11   YearsCode                       59869 non-null  str
 12   YearsCodePro                    51610 non-null  str
 13   DevType                         59445 non-null  str
 14   OrgSize                         47480 non-null  str
 15   PurchaseInfluence               47406 non-null  str
 16   BuyNewTool                      45181 non-null  str
 17   BuildvsBuy                      43358 non-null  str
 18   TechEndorse                     43668 non-null  str
 19   Country                         58930 non-null  str
 20   Currency                        46684 non-null  str
 21   CompTotal                       33740 non-null  float64
 22   LanguageHaveWorkedWith          59745 non-null  str
 23   LanguageWantToWorkWith          55752 non-null  str
 24   LanguageAdmired                 50872 non-null  str
 25   DatabaseHaveWorkedWith          50254 non-null  str
 26   DatabaseWantToWorkWith          42558 non-null  str
 27   DatabaseAdmired                 38557 non-null  str
 28   PlatformHaveWorkedWith          42366 non-null  str
 29   PlatformWantToWorkWith          34532 non-null  str
 30   PlatformAdmired                 31377 non-null  str
 31   WebframeHaveWorkedWith          45161 non-null  str
 32   WebframeWantToWorkWith          38535 non-null  str
 33   WebframeAdmired                 34943 non-null  str
 34   EmbeddedHaveWorkedWith          22214 non-null  str
 35   EmbeddedWantToWorkWith          17600 non-null  str
 36   EmbeddedAdmired                 16733 non-null  str
 37   MiscTechHaveWorkedWith          39443 non-null  str
 38   MiscTechWantToWorkWith          32964 non-null  str
 39   MiscTechAdmired                 29596 non-null  str
 40   ToolsTechHaveWorkedWith         52482 non-null  str
 41   ToolsTechWantToWorkWith         46084 non-null  str
 42   ToolsTechAdmired                43997 non-null  str
 43   NEWCollabToolsHaveWorkedWith    57592 non-null  str
 44   NEWCollabToolsWantToWorkWith    52087 non-null  str
 45   NEWCollabToolsAdmired           50711 non-null  str
 46   OpSysPersonal use               58174 non-null  str
 47   OpSysProfessional use           52973 non-null  str
 48   OfficeStackAsyncHaveWorkedWith  48093 non-null  str
 49   OfficeStackAsyncWantToWorkWith  38966 non-null  str
 50   OfficeStackAsyncAdmired         37204 non-null  str
 51   OfficeStackSyncHaveWorkedWith   55545 non-null  str
 52   OfficeStackSyncWantToWorkWith   46711 non-null  str
 53   OfficeStackSyncAdmired          44712 non-null  str
 54   AISearchDevHaveWorkedWith       44453 non-null  str
 55   AISearchDevWantToWorkWith       36701 non-null  str
 56   AISearchDevAdmired              35543 non-null  str
 57   NEWSOSites                      60286 non-null  str
 58   SOVisitFreq                     59536 non-null  str
 59   SOAccount                       59560 non-null  str
 60   SOPartFreq                      45237 non-null  str
 61   SOHow                           58962 non-null  str
 62   SOComm                          59163 non-null  str
 63   AISelect                        60907 non-null  str
 64   AISent                          45873 non-null  str
 65   AIBen                           36894 non-null  str
 66   AIAcc                           37302 non-null  str
 67   AIComplex                       37021 non-null  str
 68   AIToolCurrently Using           35072 non-null  str
 69   AIToolInterested in Using       30691 non-null  str
 70   AIToolNot interested in Using   24414 non-null  str
 71   AINextMuch more integrated      13438 non-null  str
 72   AINextNo change                 12498 non-null  str
 73   AINextMore integrated           24428 non-null  str
 74   AINextLess integrated           2355 non-null   str
 75   AINextMuch less integrated      1148 non-null   str
 76   AIThreat                        44689 non-null  str
 77   AIEthics                        41548 non-null  str
 78   AIChallenges                    37531 non-null  str
 79   TBranch                         44477 non-null  str
 80   ICorPM                          29801 non-null  str
 81   WorkExp                         29658 non-null  float64
 82   Knowledge_1                     28664 non-null  str
 83   Knowledge_2                     28021 non-null  str
 84   Knowledge_3                     28095 non-null  str
 85   Knowledge_4                     28030 non-null  str
 86   Knowledge_5                     27880 non-null  str
 87   Knowledge_6                     27864 non-null  str
 88   Knowledge_7                     27778 non-null  str
 89   Knowledge_8                     27758 non-null  str
 90   Knowledge_9                     27635 non-null  str
 91   Frequency_1                     28369 non-null  str
 92   Frequency_2                     28364 non-null  str
 93   Frequency_3                     27710 non-null  str
 94   TimeSearching                   28911 non-null  str
 95   TimeAnswering                   28844 non-null  str
 96   Frustration                     28251 non-null  str
 97   ProfessionalTech                27764 non-null  str
 98   ProfessionalCloud               28491 non-null  str
 99   ProfessionalQuestion            28807 non-null  str
 100  Industry                        28858 non-null  str
 101  JobSatPoints_1                  29324 non-null  float64
 102  JobSatPoints_4                  29393 non-null  float64
 103  JobSatPoints_5                  29411 non-null  float64
 104  JobSatPoints_6                  29450 non-null  float64
 105  JobSatPoints_7                  29448 non-null  float64
 106  JobSatPoints_8                  29456 non-null  float64
 107  JobSatPoints_9                  29456 non-null  float64
 108  JobSatPoints_10                 29450 non-null  float64
 109  JobSatPoints_11                 29445 non-null  float64
 110  SurveyLength                    56182 non-null  str
 111  SurveyEase                      56238 non-null  str
 112  ConvertedCompYearly             23435 non-null  float64
 113  JobSat                          29126 non-null  float64
dtypes: float64(13), int64(1), str(100)
memory usage: 56.9 MB
None

<h5>2.2 Generate basic statistics for numerical columns.</h5>

In [21]:
# Write your code here
df.describe()

,ResponseId,CompTotal,WorkExp,JobSatPoints_1,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,ConvertedCompYearly,JobSat
count,65437.000000,3.374000e+04,29658.000000,29324.000000,29393.000000,29411.000000,29450.000000,29448.00000,29456.000000,29456.000000,29450.000000,29445.000000,2.343500e+04,29126.000000
mean,32719.000000,2.963841e+145,11.466957,18.581094,7.522140,10.060857,24.343232,22.96522,20.278165,16.169432,10.955713,9.953948,8.615529e+04,6.935041
std,18890.179119,5.444117e+147,9.168709,25.966221,18.422661,21.833836,27.089360,27.01774,26.108110,24.845032,22.906263,21.775652,1.867570e+05,2.088259
min,1.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,1.000000e+00,0.000000
25%,16360.000000,6.000000e+04,4.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,3.271200e+04,6.000000
50%,32719.000000,1.100000e+05,9.000000,10.000000,0.000000,0.000000,20.000000,15.00000,10.000000,5.000000,0.000000,0.000000,6.500000e+04,7.000000
75%,49078.000000,2.500000e+05,16.000000,22.000000,5.000000,10.000000,30.000000,30.00000,25.000000,20.000000,10.000000,10.000000,1.079715e+05,8.000000
max,65437.000000,1.000000e+150,50.000000,100.000000,100.000000,100.000000,100.000000,100.00000,100.000000,100.000000,100.000000,100.000000,1.625660e+07,10.000000

### 3. Identifying and Removing Inconsistencies

<h5>3.1 Identify inconsistent or irrelevant entries in specific columns (e.g., Country).</h5>

In [22]:
# Write your code here
with pd.option_context('display.max_rows', None):
    display(df['Country'].value_counts())

Country
United States of America                                11095
Germany                                                  4947
India                                                    4231
United Kingdom of Great Britain and Northern Ireland     3224
Ukraine                                                  2672
France                                                   2110
Canada                                                   2104
Poland                                                   1534
Netherlands                                              1449
Brazil                                                   1375
Italy                                                    1341
Australia                                                1260
Spain                                                    1123
Sweden                                                   1016
Russian Federation                                        925
Switzerland                                               876
Austria                                                   791
Czech Republic                                            714
Israel                                                    604
Turkey                                                    546
Belgium                                                   526
Denmark                                                   504
Portugal                                                  470
Norway                                                    450
Romania                                                   439
Pakistan                                                  415
Iran, Islamic Republic of...                              411
China                                                     406
Mexico                                                    402
Hungary                                                   396
New Zealand                                               396
Greece                                                    389
Finland                                                   386
South Africa                                              358
Indonesia                                                 354
Argentina                                                 345
Bangladesh                                                327
Bulgaria                                                  319
Nigeria                                                   305
Viet Nam                                                  296
Japan                                                     288
Ireland                                                   270
Taiwan                                                    268
Egypt                                                     262
Slovakia                                                  248
Serbia                                                    245
Colombia                                                  217
Philippines                                               196
Croatia                                                   187
Lithuania                                                 183
Kenya                                                     180
Singapore                                                 177
Sri Lanka                                                 163
Malaysia                                                  161
Thailand                                                  147
South Korea                                               146
Hong Kong (S.A.R.)                                        146
Slovenia                                                  142
Nepal                                                     139
Chile                                                     133
United Arab Emirates                                      130
Latvia                                                    128
Estonia                                                   110
Morocco                                                    98
Belarus                                                    97
Georgia                                                    94
Uruguay                                                    94
Kazakhstan                                                 81
Algeria                                                    77
Peru                                                       75
Tunisia                                                    71
Ghana                                                      70
Venezuela, Bolivarian Republic of...                       69
Cyprus                                                     63
Uzbekistan                                                 62
Bosnia and Herzegovina                                     62
Ethiopia                                                   60
Armenia                                                    58
Republic of Korea                                          57
Saudi Arabia                                               56
Afghanistan                                                56
Ecuador                                                    54
Costa Rica                                                 54
Albania                                                    49
Dominican Republic                                         47
Lebanon                                                    46
Iraq                                                       44
Kyrgyzstan                                                 44
Nomadic                                                    43
Guatemala                                                  41
Luxembourg                                                 40
Jordan                                                     40
Paraguay                                                   39
Uganda                                                     39
Republic of Moldova                                        38
Republic of North Macedonia                                36
Bolivia                                                    32
Iceland                                                    31
Cameroon                                                   31
Syrian Arab Republic                                       30
Malta                                                      29
United Republic of Tanzania                                28
Azerbaijan                                                 27
Montenegro                                                 27
Zimbabwe                                                   26
Cuba                                                       23
Rwanda                                                     22
Cambodia                                                   22
Nicaragua                                                  21
Myanmar                                                    21
Angola                                                     20
El Salvador                                                19
Kosovo                                                     18
Panama                                                     18
Yemen                                                      18
Maldives                                                   16
Honduras                                                   16
Palestine                                                  15
Mauritius                                                  15
Zambia                                                     15
Andorra                                                    15
Qatar                                                      15
Madagascar                                                 14
Côte d'Ivoire                                              14
Isle of Man                                                13
Malawi                                                     12
Jamaica                                                    11
Benin                                                      11
Turkmenistan                                               11
Bahrain                                                    11
Mongolia                                                   10
Senegal                                                     9
Somalia                                                     9
Togo                                                        9
Kuwait                                                      8
Trinidad and Tobago                                         8
Oman                                                        8
Congo, Republic of the...                                   8
Tajikistan                                                  7
Sudan                                                       7
Mozambique                                                  7
Barbados                                                    6
Namibia                                                     5
Mauritania                                                  5
Botswana                                                    5
Suriname                                                    5
Cape Verde                                                  5
Antigua and Barbuda                                         5
Liechtenstein                                               4
Fiji                                                        4
Gabon                                                       4
Bahamas                                                     4
Lao People's Democratic Republic                            4
Swaziland                                                   4
Burkina Faso                                                4
Libyan Arab Jamahiriya                                      4
Liberia                                                     4
San Marino                                                  3
Democratic Republic of the Congo                            3
Burundi                                                     3
Sierra Leone                                                3
North Korea                                                 3
Guyana                                                      3
Brunei Darussalam                                           3
Bhutan                                                      3
Monaco                                                      3
Democratic People's Republic of Korea                       2
Guinea-Bissau                                               2
Belize                                                      2
Mali                                                        2
Dominica                                                    1
Papua New Guinea                                            1
Central African Republic                                    1
Equatorial Guinea                                           1
Guinea                                                      1
Niger                                                       1
Samoa                                                       1
Lesotho                                                     1
Saint Kitts and Nevis                                       1
Micronesia, Federated States of...                          1
Haiti                                                       1
Nauru                                                       1
Chad                                                        1
Djibouti                                                    1
Solomon Islands                                             1
Name: count, dtype: int64

<h5>3.2 Standardize entries in columns like Country or EdLevel by mapping inconsistent values to a consistent format.</h5>

In [23]:
## Write your code here
df['Country'] = df['Country'].replace({'United States of America':'USA',
                                       'United Kingdom of Great Britain and Northern Ireland':'UK',
                                       'Republic of Korea':'South Korea',
                                       'Iran, Islamic Republic of...' : 'Iran',
                                       "Democratic People's Republic of Korea" : 'North Korea',
                                       'Venezuela, Bolivarian Republic of...':'Venezuela',
                                       'Micronesia, Federated States of...':'Micronesia',
                                      'Congo, Republic of the...':'Congo',
                                      'Democratic Republic of the Congo':'Congo'})

### 4. Encoding Categorical Variables

<h5>4.1 Encode the Employment column using one-hot encoding.</h5>

In [17]:
## Write your code here
df = pd.get_dummies(df,columns=['Employment'],prefix='Emp')

### 5. Handling Missing Values

<h5>5.1 Identify columns with the highest number of missing values.</h5>

In [34]:
## Write your code here
df.isnull().sum().sort_values(ascending=False)

AINextMuch less integrated    64289
AINextLess integrated         63082
AINextNo change               52939
AINextMuch more integrated    51999
EmbeddedAdmired               48704
                              ...
MainBranch                        0
Age                               0
Employment                        0
Check                             0
ResponseId                        0
Length: 114, dtype: int64

<h5>5.2 Impute missing values in numerical columns (e.g., `ConvertedCompYearly`) with the mean or median.</h5>

In [35]:
## Write your code here
mean = df['ConvertedCompYearly'].mean()
df['ConvertedCompYearly'] = df['ConvertedCompYearly'].fillna(mean)

<h5>5.3 Impute missing values in categorical columns (e.g., `RemoteWork`) with the most frequent value.</h5>

In [36]:
## Write your code here
mode = df['RemoteWork'].mode()
df['RemoteWork'] = df['RemoteWork'].fillna(mode)

### 6. Feature Scaling and Transformation

<h5>6.1 Apply Min-Max Scaling to normalize the `ConvertedCompYearly` column.</h5>

In [52]:
## Write your code here
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
df['ConvertedCompYearly'] = scaler.fit_transform(df[['ConvertedCompYearly']])

<h5>6.2 Log-transform the ConvertedCompYearly column to reduce skewness.</h5>

In [58]:
## Write your code here
import numpy as np

df['ConvertedCompYearly_Log'] = np.log1p(df['ConvertedCompYearly'])

### 7. Feature Engineering

<h5>7.1 Create a new column `ExperienceLevel` based on the `YearsCodePro` column:</h5>

In [60]:
## Write your code here
df['YearsCodePro'] = df['YearsCodePro'].replace({
    'Less than 1 year': 0,
    'More than 50 years': 51
})

df['YearsCodePro'] = pd.to_numeric(df['YearsCodePro'], errors='coerce').fillna(0)

def categorize_experience(years):
    if years <= 2:
        return 'Junior'
    elif years <= 5:
        return 'Intermediate'
    elif years <= 10:
        return 'Senior'
    else:
        return 'Expert'


df['ExperienceLevel'] = df['YearsCodePro'].apply(categorize_experience)

### Summary

In [61]:
df[['YearsCodePro', 'ExperienceLevel']].head()

   YearsCodePro ExperienceLevel
0           0.0          Junior
1          17.0          Expert
2          27.0          Expert
3           0.0          Junior
4           0.0          Junior

In this lab, you:

- Explored the dataset to identify inconsistencies and missing values.

- Encoded categorical variables for analysis.

- Handled missing values using imputation techniques.

- Normalized and transformed numerical data to prepare it for analysis.

- Engineered a new feature to enhance data interpretation.

Copyright © IBM Corporation. All rights reserved.